import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import type { Types } from "mongoose";

import dbConnect from "@/lib/mongodb";
import { Event, type Event as EventType } from "@/database/event.model";

// Ensure this endpoint is always dynamic (avoids accidental caching of DB reads).
export const dynamic = "force-dynamic";

type ApiError = {
  message: string;
};

type EventLean = EventType & {
  _id: Types.ObjectId;
  slug?: string;
  createdAt?: Date;
  updatedAt?: Date;
};

type GetEventSuccess = {
  event: EventLean;
};

type RouteContext = {
  // Next.js 16+ types `params` as a Promise.
  params: Promise<{
    slug: string;
  }>;
};

const jsonError = (status: number, message: string): NextResponse<ApiError> =>
  NextResponse.json({ message }, { status });

const normalizeSlug = (raw: string): string => raw.trim().toLowerCase();

// Matches slugs generated by `toSlug()` in `database/event.model.ts`.
const isValidSlug = (slug: string): boolean => {
  if (slug.length === 0 || slug.length > 96) return false;
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug);
};

export async function GET(_req: NextRequest, { params }: RouteContext) {
  const { slug: rawSlug } = await params;

  if (typeof rawSlug !== "string") {
    return jsonError(400, "Missing or invalid 'slug' route parameter");
  }

  const slug = normalizeSlug(rawSlug);

  if (!isValidSlug(slug)) {
    return jsonError(
      400,
      "Invalid 'slug'. Expected lowercase letters/numbers separated by single hyphens (max 96 chars)."
    );
  }

  try {
    await dbConnect();

    // Use `lean()` for a plain JSON-friendly object and exclude internal mongoose fields.
    const event = await Event.findOne({ slug }).select("-__v").lean<EventLean>().exec();

    if (!event) {
      return jsonError(404, "Event not found");
    }

    return NextResponse.json({ event }, { status: 200 });
  } catch (err: unknown) {
    // Avoid leaking internal errors in production.
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("GET /api/events/[slug] failed:", message);
    return jsonError(500, "Unexpected server error");
  }
}
